region           = "ap-south-1"
project_name     = "zomato"
project_env      = "production"
instance_ami     = "ami-013e83f579886baeb"
instance_type    = "t2.micro"
keypair_name     = "zomato-production"
project_hostname = "www"
project_domain   = "msafvan.online"
